###
GET http://localhost:3000

###
GET http://localhost:3000/songs

###
POST http://localhost:3000/songs
Content-Type: application/json

{
  "title": "Sharks",
  "artists": ["Imagine Dragons"],
  "duration": "03:01",
  "releasedDate": "2005-12-06"
}

###
GET http://localhost:3000/songs/123f