###
GET http://localhost:3000

### Get all (default paginate)
GET http://localhost:3000/songs

### Get all
GET http://localhost:3000/songs?limit=1&page=2

### Get by id
GET http://localhost:3000/songs/2

### Create
POST http://localhost:3000/songs
Content-Type: application/json

{
  "title": "Машина для убийств",
  "artists": [1, 2],
  "lyrics": "Lal lalaal laalla al lal lalalal lalala.",
  "duration": "03:01",
  "releasedDate": "2005-12-12"
}

### Update
PUT http://localhost:3000/songs/1
Content-Type: application/json

{
  "artists": [2],
  "title": "Believer",
  "duration": "02:55"
}

### Delete by id
DELETE http://localhost:3000/songs/4

### Create playlist
POST http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "favourites",
  "user": 4,
  "songs": [3, 13]
}


### Register user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "firstName": "coco",
  "lastName": "sh",
  "email": "coco@co.co",
  "password": "123456"
}

### Login user using JWT
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "coco@co.co",
  "password": "123456"
}

### Profile
GET http://localhost:3000/profile
Content-Type: application/json