###
GET http://localhost:3000

### Get all (default paginate)
GET http://localhost:3000/songs

### Get all
GET http://localhost:3000/songs?limit=1&page=2

### Get by id
GET http://localhost:3000/songs/2

### Create
POST http://localhost:3000/songs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvY29AY28uY28iLCJ1c2VySWQiOjksImFydGlzdElkIjo2LCJpYXQiOjE3MjIyNTI3NjJ9.EzikzUAoN1o18XLTC9uOwIEMpKBzfRar64pW5CggTeg

{
  "title": "Unauthorized Artist",
  "artists": [6],
  "lyrics": "Lal lalaal laalla al lal lalalal lalala.",
  "duration": "01:01",
  "releasedDate": "2024-05-18"
}

### Update
PUT http://localhost:3000/songs/1
Content-Type: application/json

{
  "artists": [2],
  "title": "Believer",
  "duration": "02:55"
}

### Delete by id
DELETE http://localhost:3000/songs/4

### Create playlist
POST http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "favourites",
  "user": 4,
  "songs": [3, 13]
}


### Register user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "firstName": "coco",
  "lastName": "sh",
  "email": "coco@co.co",
  "password": "123456"
}

### Login user using JWT
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "coco@co.co",
  "password": "123456"
}

### Profile
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvY29AY28uY28iLCJ1c2VySWQiOjksImFydGlzdElkIjo2LCJpYXQiOjE3MjIyNTI3NjJ9.EzikzUAoN1o18XLTC9uOwIEMpKBzfRar64pW5CggTeg
Content-Type: application/json

### Enable 2FA
GET http://localhost:3000/auth/enable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvY29AY28uY28iLCJ1c2VySWQiOjksImFydGlzdElkIjo2LCJpYXQiOjE3MjIyNTI3NjJ9.EzikzUAoN1o18XLTC9uOwIEMpKBzfRar64pW5CggTeg

### Validate 2FA
POST http://localhost:3000/auth/validate-2fa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvY29AY28uY28iLCJ1c2VySWQiOjksImFydGlzdElkIjo2LCJpYXQiOjE3MjIyNzU5Mjl9.M79dL-_5ugqkEAQzVAIxTCSSJy8-e49qUi44z0Kj76Q

{
  "token": "444071"
}

### Disavle 2FA
GET http://localhost:3000/auth/disable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvY29AY28uY28iLCJ1c2VySWQiOjksImFydGlzdElkIjo2LCJpYXQiOjE3MjIyNTI3NjJ9.EzikzUAoN1o18XLTC9uOwIEMpKBzfRar64pW5CggTeg
